version: "3.9"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
<<<<<<< HEAD
      - db
=======
      - db
>>>>>>> 9c8328b1e52c206ac46a43aebfc89c9062745086
