# Generated by Django 4.0.4 on 2022-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Very good', 'Very good'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory')], default='New', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Unisex', 'Unisex'), ('M', 'Male'), ('F', 'Female')], default='Unisex', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS')], default='XXL', max_length=3),
        ),
    ]
