# Generated by Django 4.0.4 on 2022-05-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_product_condition_product_sex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('Jumper', 'Jumper'), ('T-shirts', 'T-shirts'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater'), ('Pants', 'Pants'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Other', 'Other')], default='Other', max_length=8),
        ),
    ]
