# Generated by Django 4.0.4 on 2022-05-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('T-shirts', 'T-shirts'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater'), ('Pants', 'Pants'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
