# Generated by Django 4.0.4 on 2022-05-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
