# Generated by Django 4.0.4 on 2022-05-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('Sweatshirt', 'Sweatshirt'), ('T-shirt', 'T-shirt'), ('Jacket', 'Jacket'), ('Sweater', 'Sweater'), ('Pants', 'Pants'), ('Shirt', 'Shirt'), ('Shoes', 'Shoes'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
